### ISSUE TITLE
'latest' should point to 7.1.0

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PowerShell-Docker#527]
The 'latest' tag still points to `7.0.3`. It should point to `7.1.0`

In addition there is no `lts` tag, that should point at what `latest` is now.

# work items
- [x] update createAllManifests.ps1 file to use meta.json files to build the manifest lists
- [x] update the release to release the manifest lists mentioned in the meta.json files
- [ ] add the lts tag
    - [ ] Update the build to also build manifest lists for lts
    - [ ] update meta.json files appropriately

**Comment by anamnavi** [comment]
https://github.com/PowerShell/PowerShell-Docker/blob/master/.vsts-ci/templatesReleasePipeline/releaseJob.yml#L83

https://github.com/PowerShell/PowerShell-Docker/blob/master/createAllManifests.ps1

(need to push the createAllManifests.ps1 file, using the command in the releaseJob.yml file). Create lts tag in the creatAllManifest file

**Comment by TravisEz13** [comment]
I've done the work to fix the fact that latest wasn't being released after I rewrote the release process.  I'm leaving the LTS tag to @anamnavi, but almost anyone should be able to do it now.

**Comment by anamnavi** [comment]
Will start work on the LTS tag tomorrow :)

**Comment by JustinGrote** [comment]
Thanks guys, the quick response is much appreciated.

**Comment by TravisEz13** [comment]
@JustinGrote Sorry, I didn't notice I broke it when I reworked the release system.  Thanks for finding it.

**Comment by TravisEz13** [comment]
fixed by #532

**Comment by TravisEz13** [comment]
I just released that.
